#!/bin/sh
# Install some standard GyMo plugins
/Applications/Eclipse.app/Contents/MacOS/eclipse -nosplash \
-application org.eclipse.equinox.p2.director \
-repository  http://lejos.sourceforge.net/tools/eclipse/plugin/ev3,http://www.lejos.org/tools/eclipse/plugin/nxj,http://download.eclipse.org/releases/mars \
-destination /Applications/Eclipse.app/Contents/Eclipse \
-installIUs org.lejos.ev3.ldt.feature.feature.group,org.lejos.nxt.ldt.feature.feature.group,org.eclipse.ant.core



